verify manual hilla version

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -70,7 +70,7 @@ jobs:
             exit 1
           fi
           if [[ "${{ inputs.target-branch }}" != "main" && ! "${{ inputs.version }}" = "${{ inputs.target-branch }}."* ]]; then
-            echo "ERROR: Invalid version specified: '${{ inputs.version }}' does not match the release branch '${{ inputs.target-branch }}'." \
+            echo "🚫 Invalid version specified: '${{ inputs.version }}' does not match the release branch '${{ inputs.target-branch }}'." \
              | tee -a  $GITHUB_STEP_SUMMARY
             exit 1
           fi
@@ -86,14 +86,20 @@ jobs:
       - name: Pin Hilla version
         run: |
           if [[ -n "${{ inputs.hilla-version }}" ]]; then
-            mvn -N -ntp versions:set-property -Dproperty=hilla.version -DnewVersion="${{ inputs.hilla-version }}"
-            echo "Hilla version set to ${{ inputs.hilla-version }}." | tee -a  $GITHUB_STEP_SUMMARY
+            if [[ "${{ inputs.hilla-version }}" = "${{ inputs.target-branch }}."* ]]; then            
+              mvn -N -ntp versions:set-property -Dproperty=hilla.version -DnewVersion="${{ inputs.hilla-version }}"
+              echo "⚠️ Hilla version set to ${{ inputs.hilla-version }}." | tee -a  $GITHUB_STEP_SUMMARY
+            elif
+              echo "🚫 Hilla version '${{ inputs.hilla-version }}' does not match release branch ${{ inputs.target-branch }}." \
+                | tee -a  $GITHUB_STEP_SUMMARY
+              exit 1
+            fi
           fi
           hilla_version=$(mvn -ntp -N -q help:evaluate -Dexpression=hilla.version -DforceStdout)
           if [[ "$hilla_version" =~ .*-SNAPSHOT ]]; then
             mvn -N -ntp -Dproperty=hilla.version -DallowMinorUpdates=false -DgenerateBackupPoms=false -Dmaven.version.rules=file://$(pwd)/etc/release-version-rules.xml versions:update-property
             hilla_version=$(mvn -ntp -N -q help:evaluate -Dexpression=hilla.version -DforceStdout)
-            echo "Autodetected Hilla version $hilla_version." | tee -a  $GITHUB_STEP_SUMMARY
+            echo "⚠️ Autodetected Hilla version $hilla_version." | tee -a  $GITHUB_STEP_SUMMARY
           elif
             echo "Hilla version $hilla_version." | tee -a  $GITHUB_STEP_SUMMARY
           fi
