chore(actions): improve release process (#404)
Improvements to the release process:

- allow specifying the pinned Hilla version manually
- autodetect latest Hilla release or pre-release if version in POM is a SNAPSHOT
- Skip tests in dry-run execution to get faster feedback

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -17,6 +17,12 @@ on:
         description: "Version to release (e.g. 1.1.0 or 1.2.0-alpha1)"
         required: true
         type: string
+      hilla-version:
+        description: |
+          Version of Hilla to pin for this release. If not provided, the value of the hilla.version property in will be used.
+          If the Hilla version is a SNAPSHOT, the latest available release compatible with quarkus-hilla major.minor will be used.
+        required: false
+        type: string
       dry-run:
         description: "Dry run (skips remote operations)"
         required: true
@@ -40,6 +46,7 @@ jobs:
           echo "🚫 **${{ github.actor }}** is an external contributor, only **${{ github.repository }}** team members can perform a release" \
             | tee -a $GITHUB_STEP_SUMMARY && exit 1
       - name: Validate Workflow branch
+        if: ${{ !github.event.inputs.dry-run }}
         run: |
           BRANCH_NAME=${GITHUB_REF##*/}
           if [[ "main" != "${BRANCH_NAME}" ]]; then
@@ -63,7 +70,7 @@ jobs:
             exit 1
           fi
           if [[ "${{ inputs.target-branch }}" != "main" && ! "${{ inputs.version }}" = "${{ inputs.target-branch }}."* ]]; then
-            echo "ERROR: Invalid version specified: '${{ inputs.version }}' does not match the release branch '${{ inputs.target-branch }}'." \
+            echo "🚫 Invalid version specified: '${{ inputs.version }}' does not match the release branch '${{ inputs.target-branch }}'." \
              | tee -a  $GITHUB_STEP_SUMMARY
             exit 1
           fi
@@ -72,9 +79,35 @@ jobs:
              | tee -a  $GITHUB_STEP_SUMMARY
             exit 1
           fi
-          echo "Releasing version '${{ inputs.version }}' from branch '${{ inputs.target-branch }}'." >> $GITHUB_STEP_SUMMARY
+          echo "Releasing version '${{ inputs.version }}' from branch '${{ inputs.target-branch }}'." | tee -a $GITHUB_STEP_SUMMARY
           if [[ "${{ github.event.inputs.dry-run }}" == "true" ]]; then
-            echo "⚠️ dry-run execution, artifacts will not be published on Maven Central." >> $GITHUB_STEP_SUMMARY
+            echo "⚠️ dry-run execution, artifacts will not be published on Maven Central." | tee -a $GITHUB_STEP_SUMMARY
+          fi
+      - name: Pin Hilla version
+        run: |
+          hilla_version=$(mvn -ntp -N -q help:evaluate -Dexpression=hilla.version -DforceStdout)
+          hilla_version_major_minor=$(echo "${hilla_version/-*/}" | cut -d. -f1,2)
+          echo "POM file Hilla version: $hilla_version." | tee -a  $GITHUB_STEP_SUMMARY
+          if [[ -n "${{ inputs.hilla-version }}" ]]; then
+            if [[ "${{ inputs.hilla-version }}" = "${hilla_version_major_minor}."* ]]; then
+              mvn -N -ntp versions:set-property -Dproperty=hilla.version -DnewVersion="${{ inputs.hilla-version }}"
+              echo "⚠️ Hilla version manually forced to ${{ inputs.hilla-version }}." | tee -a  $GITHUB_STEP_SUMMARY
+              hilla_version="${{ inputs.hilla-version }}"
+            else
+              echo "🚫 Forced Hilla version '${{ inputs.hilla-version }}' does not match Hilla version on release branch '$hilla_version_major_minor'." \
+                | tee -a $GITHUB_STEP_SUMMARY
+              exit 1
+            fi
+          fi
+          if [[ "$hilla_version" =~ .*-SNAPSHOT ]]; then
+            mvn -N -ntp -Dproperty=hilla.version -DallowMinorUpdates=false -DgenerateBackupPoms=false -Dmaven.version.rules=file://$(pwd)/etc/release-version-rules.xml versions:update-property
+            hilla_version=$(mvn -ntp -N -q help:evaluate -Dexpression=hilla.version -DforceStdout)
+            echo "⚠️ SNAPSHOT detected for Hilla version. Automatically forcing version to $hilla_version." | tee -a $GITHUB_STEP_SUMMARY
+          fi
+          if [[ "$hilla_version" =~ .*-SNAPSHOT ]]; then
+            echo "🚫 Hilla version '${{ inputs.hilla-version }}' is a SNAPSHOT. Please provide a proper release version." \
+             | tee -a $GITHUB_STEP_SUMMARY
+            exit 1
           fi
       - name: Setup Java
         uses: actions/setup-java@v3
@@ -84,7 +117,7 @@ jobs:
 
       - name: Staging artifacts
         run: |
-          mvn -V -ntp -Pdistribution,default-modules -Drevision=${{ inputs.version }} -DaltDeploymentRepository=local::file:./target/staging-deploy deploy
+          mvn -V -ntp -Pdistribution,default-modules -Drevision=${{ inputs.version }} -DaltDeploymentRepository=local::file:./target/staging-deploy ${{ github.event.inputs.dry-run && '-DskipTests' || '' }} deploy
 
       - name: Run JReleaser
         env:
@@ -96,7 +129,7 @@ jobs:
           JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
           JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
         run: |
-          mvn -N -V -ntp -Pdistribution -Drevision=${{ inputs.version }} -Djreleaser.dry.run="${{ github.event.inputs.dry-run }}" jreleaser:full-release
+          mvn -N -V -ntp -Pdistribution -Drevision=${{ inputs.version }} -Djreleaser.dry.run="${{ github.event.inputs.dry-run }}" ${{ github.event.inputs.dry-run && '-DskipTests' || '' }} jreleaser:full-release
 
       - name: JReleaser release output
         if: always()
