chore(actions): add formatting check and auto-format PR jobs (#78)
A new job in validation workflow checks that formatting is ok, and if not, it prevents the PR from being merged.
If the code is not well formatted, the label format:required is applied to the PR and a comment reports the file that should be checked, a full diff and formatting instructions.
Otherwise, the format:checked label is applied.

Another workflow, triggered by the auto-format label, applies formatting to the PR and pushes the changes to the PR branch.
The push automatically triggers a new validation.

Closes #67
Closes #68

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -16,8 +16,7 @@ concurrency:
 env:
   JAVA_VERSION: 17
 jobs:
-  build-and-test:
-    timeout-minutes: 30
+  check-permissions:
     runs-on: ubuntu-22.04
     steps:
       - run: echo "Concurrency Group = ${{ github.head_ref || github.ref_name }}"
@@ -31,6 +30,11 @@ jobs:
         run: |
           echo "🚫 **${{ github.actor }}** is an external contributor, a **${{ github.repository }}** team member has to review this changes and re-run this build" \
             | tee -a $GITHUB_STEP_SUMMARY && exit 1
+  build-and-test:
+    needs: [check-permissions]
+    timeout-minutes: 30
+    runs-on: ubuntu-22.04
+    steps:
       - name: Checkout
         uses: actions/checkout@v3
         with:
@@ -66,3 +70,125 @@ jobs:
         with:
           junit_files: "**/target/*-reports/TEST*.xml"
           check_run_annotations: all tests, skipped tests
+  checkstyle:
+    needs: [check-permissions]
+    timeout-minutes: 5
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Remove format labels
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const { owner, repo } = context.repo;
+            const prNumber = context.payload.pull_request.number;
+            
+            // Remove the label if it exists
+            const existingLabels = await github.rest.issues.listLabelsOnIssue({
+              owner,
+              repo,
+              issue_number: prNumber,
+            });
+            const labelsToRemove = existingLabels.data.map(label => label.name).filter( label => label.startsWith("format:") );
+            for (const labelToRemove of labelsToRemove) {
+              await github.rest.issues.removeLabel({
+                owner,
+                repo,
+                issue_number: prNumber,
+                name: labelToRemove,
+              });
+            }
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+      - name: Set up Java
+        uses: actions/setup-java@v3
+        with:
+          java-version: ${{ env.JAVA_VERSION }}
+          distribution: 'temurin'
+          cache: maven
+      - name: Check
+        id: spotlessCheck
+        run: |
+          set -x -e -o pipefail
+          mvn -V -e -B -ntp spotless:check
+      - name: Prepare failure message
+        if: ${{ failure() && steps.spotlessCheck.conclusion == 'failure' }}
+        run: |
+          set -x -e -o pipefail
+          mvn -V -e -B -ntp spotless:apply
+          git diff --output=/tmp/full-diff.txt 
+          git diff --name-only --output=/tmp/unformatted.txt
+          _files=$(cat /tmp/unformatted.txt | wc -l)
+          echo "### Format Checker Report" >> /tmp/message
+          echo "" >> /tmp/message
+          echo "There are **${_files} files** with format errors." >> /tmp/message
+          echo "" >> /tmp/message
+          echo '* To fix the build, please run `mvn spotless:apply` in your branch and commit the changes.' >> /tmp/message 
+          echo '* Alternatively, apply the `auto-format` label to the PR.' >> /tmp/message
+          echo "" >> /tmp/message
+          echo "" >> /tmp/message
+          echo "<details>" >> /tmp/message
+          echo "  <summary>Files with format issues in this PR</summary>" >> /tmp/message
+          echo "" >> /tmp/message
+          echo '```' >> /tmp/message
+          cat /tmp/unformatted.txt  >> /tmp/message
+          echo '```' >> /tmp/message
+          echo "</details>" >> /tmp/message
+          echo "" >> /tmp/message
+          echo "" >> /tmp/message
+          echo "<details>" >> /tmp/message
+          echo "  <summary>Full Diff</summary>" >> /tmp/message
+          echo "" >> /tmp/message
+          echo '```patch' >> /tmp/message
+          cat /tmp/full-diff.txt  >> /tmp/message
+          echo '```' >> /tmp/message
+          echo "</details>" >> /tmp/message
+      - name: Prepare success message
+        if: ${{ success() }}
+        run: |
+          set -x -e -o pipefail
+          echo "# Format Checker Report" >> /tmp/message
+          echo "" >> /tmp/message
+          echo "All files are correctly formatted" >> /tmp/message
+      - name: Comment PR
+        if: ${{ always() }}
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          filePath: /tmp/message
+          comment_tag: formatting-check
+      - name: Add format required label to PR
+        if: ${{ failure() && steps.spotlessCheck.conclusion == 'failure' }}
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const { owner, repo } = context.repo;
+            const prNumber = context.payload.pull_request.number;
+
+            await github.rest.issues.addLabels({
+              owner,
+              repo,
+              issue_number: prNumber,
+              labels: ['format:required'],
+            });
+      - name: Add format checked label to PR
+        if: ${{ success() }}
+        uses: actions/github-script@v6
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const { owner, repo } = context.repo;
+            const prNumber = context.payload.pull_request.number;
+
+            await github.rest.issues.addLabels({
+              owner,
+              repo,
+              issue_number: prNumber,
+              labels: ['format:checked'],
+            });
+
+          
+
+    
