chore: add formattting check job

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -86,17 +86,52 @@ jobs:
           distribution: 'temurin'
           cache: maven
       - name: Check
+        id: spotlessCheck
         run: |
           set -x -e -o pipefail
           mvn -V -e -B -ntp spotless:check
-      - name: Prepare message
-        if: ${{ failure() }}
+      - name: Prepare failure message
+        if: ${{ failure() && steps.spotlessCheck.conclusion == 'failure' }}
         run: |
           set -x -e -o pipefail
           git-np diff --output=/tmp/full-diff.txt 
           git-np diff --names-only --output=/tmp/unformatted.txt
-          echo "Formatt
-          
+          _files=$(wc -l /tmp/unformatted.txt)
+          echo "# Format Checker Report" >> /tmp/message
+          echo "" >> /tmp/message
+          echo "There are *${_files} files* with format errors" >> /tmp/message
+          echo "" >> /tmp/message
+          echo '* To fix the build, please run `mvn spotless:apply` in your branch and commit the changes.' >> /tmp/message 
+          echo '* In alternative apply the `automation/format` label to the PR.' >> /tmp/message
+          echo "" >> /tmp/message
+          echo "" >> /tmp/message
+          echo "Here is the list of files with format issues in your PR:" >> /tmp/message
+          echo '```' >> /tmp/message
+          cat /tmp/unformatted.txt  >> /tmp/message
+          echo '```' >> /tmp/message
+          echo "" >> /tmp/message
+          echo "" >> /tmp/message
+          echo "And here the full diff: " >> /tmp/message
+          echo "<details>" >> /tmp/message
+          echo "  <summary>Full Diff</summary>" >> /tmp/message
+          echo "" >> /tmp/message
+          echo '```patch' >> /tmp/message
+          cat /tmp/full-diff.txt  >> /tmp/message
+          echo '```' >> /tmp/message
+          echo "</details>" >> /tmp/message
+      - name: Prepare success message
+        if: ${{ success() }}
+        run: |
+          set -x -e -o pipefail
+          echo "# Format Checker Report" >> /tmp/message
+          echo "" >> /tmp/message
+          echo "All files are correctly formatted" >> /tmp/message
+      - name: Comment PR
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          filePath: /tmp/message
+          comment_tag: formatting-check
+
           
 
     
