chore(actions): parallelize test execution (#125)
Executes different types of tests in parallel to make the validation faster.
Validation jobs are skipped if the PR only modifies files that do not affect
the build or the tests (e.g. README).

Closes #117

diff --git a/.github/workflows/validation.yaml b/.github/workflows/validation.yaml
--- a/.github/workflows/validation.yaml
+++ b/.github/workflows/validation.yaml
@@ -1,7 +1,7 @@
 name: Quarkus Hilla Validation
 on:
   push:
-    branches: [main, 1.0]
+    branches: [main, '1.0']
   workflow_dispatch:
   pull_request_target:
     types: [opened, synchronize, reopened, edited]
@@ -17,7 +17,8 @@ env:
   JAVA_VERSION: 17
 jobs:
   check-permissions:
-    runs-on: ubuntu-22.04
+    name: Check User Permissions
+    runs-on: ubuntu-latest
     steps:
       - run: echo "Concurrency Group = ${{ github.head_ref || github.ref_name }}"
       - uses: actions-cool/check-user-permission@main
@@ -30,10 +31,29 @@ jobs:
         run: |
           echo "🚫 **${{ github.actor }}** is an external contributor, a **${{ github.repository }}** team member has to review this changes and re-run this build" \
             | tee -a $GITHUB_STEP_SUMMARY && exit 1
-  build-and-test:
+  changes:
+    name: Compute changes
     needs: [check-permissions]
+    runs-on: ubuntu-latest
+    outputs:
+      validation-required: ${{ steps.filter.outputs.validate }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+      - uses: dorny/paths-filter@v2
+        id: filter
+        with:
+          filters: |
+            validate:
+              - '!(README.md|LICENSE|.gitignore|etc/**)'
+  build-and-test:
+    name: Build and test
+    needs: [changes]
+    if: ${{ needs.changes.outputs.validation-required == 'true' }}
     timeout-minutes: 30
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
@@ -56,57 +76,21 @@ jobs:
         run: |
           set -x -e -o pipefail
           mvn -V -e -B -ntp verify -Dmaven.javadoc.skip=false -DtrimStackTrace=false
-      - name: End to end Test (Development mode)
-        run: |
-          set -x -e -o pipefail
-          mvn -V -e -B -ntp verify -Dmaven.javadoc.skip=false -DtrimStackTrace=false -Pit-tests
-      - name: End to end Test (Production mode)
-        run: |
-          set -x -e -o pipefail
-          mvn -V -e -B -ntp verify -Dmaven.javadoc.skip=false -DtrimStackTrace=false -Pit-tests,production
       - name: Package test output files
         if: ${{ failure() || success() }}
-        run: find . -name surefire-reports -o -name failsafe-reports -o -name error-screenshots | tar -czf tests-report.tgz -T -
+        run: find . -name surefire-reports -o -name failsafe-reports -o -name error-screenshots | tar -czf tests-report-main.tgz -T -
       - uses: actions/upload-artifact@v3
         if: ${{ failure() || success() }}
         with:
           name: tests-output
-          path: tests-report.tgz
-      - name: Publish Unit Test Results
-        if: ${{ failure() || success() }}
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        with:
-          junit_files: "**/target/*-reports/TEST*.xml"
-          check_run_annotations: all tests, skipped tests
-  checkstyle:
-    needs: [check-permissions]
-    timeout-minutes: 5
-    runs-on: ubuntu-22.04
-    if: github.event_name == 'pull_request_target'
+          path: tests-report-*.tgz
+  e2e-dev-tests:
+    name: End-to-end tests (Development)
+    needs: [changes]
+    if: ${{ needs.changes.outputs.validation-required == 'true' }}
+    timeout-minutes: 30
+    runs-on: ubuntu-latest
     steps:
-      - name: Remove format labels
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const { owner, repo } = context.repo;
-            const prNumber = context.payload.pull_request.number;
-            
-            // Remove the label if it exists
-            const existingLabels = await github.rest.issues.listLabelsOnIssue({
-              owner,
-              repo,
-              issue_number: prNumber,
-            });
-            const labelsToRemove = existingLabels.data.map(label => label.name).filter( label => label.startsWith("format:") );
-            for (const labelToRemove of labelsToRemove) {
-              await github.rest.issues.removeLabel({
-                owner,
-                repo,
-                issue_number: prNumber,
-                name: labelToRemove,
-              });
-            }
       - name: Checkout
         uses: actions/checkout@v3
         with:
@@ -117,87 +101,91 @@ jobs:
           java-version: ${{ env.JAVA_VERSION }}
           distribution: 'temurin'
           cache: maven
-      - name: Check
-        id: spotlessCheck
+      - uses: browser-actions/setup-chrome@latest
+        with:
+          chrome-version: stable
+      - name: Build
         run: |
           set -x -e -o pipefail
-          mvn -V -e -B -ntp spotless:check
-      - name: Prepare failure message
-        if: ${{ failure() && steps.spotlessCheck.conclusion == 'failure' }}
+          mvn -V -e -B -ntp -DskipTests -Dmaven.javadoc.skip=false install
+      - name: End-to-end Test (Development mode)
         run: |
           set -x -e -o pipefail
-          mvn -V -e -B -ntp spotless:apply
-          git diff --output=/tmp/full-diff.txt 
-          git diff --name-only --output=/tmp/unformatted.txt
-          _files=$(cat /tmp/unformatted.txt | wc -l)
-          echo "### Format Checker Report" >> /tmp/message
-          echo "" >> /tmp/message
-          echo "There are **${_files} files** with format errors." >> /tmp/message
-          echo "" >> /tmp/message
-          echo '* To fix the build, please run `mvn spotless:apply` in your branch and commit the changes.' >> /tmp/message 
-          echo '* Alternatively, apply the `auto-format` label to the PR.' >> /tmp/message
-          echo "" >> /tmp/message
-          echo "" >> /tmp/message
-          echo "<details>" >> /tmp/message
-          echo "  <summary>Files with format issues in this PR</summary>" >> /tmp/message
-          echo "" >> /tmp/message
-          echo '```' >> /tmp/message
-          cat /tmp/unformatted.txt  >> /tmp/message
-          echo '```' >> /tmp/message
-          echo "</details>" >> /tmp/message
-          echo "" >> /tmp/message
-          echo "" >> /tmp/message
-          echo "<details>" >> /tmp/message
-          echo "  <summary>Full Diff</summary>" >> /tmp/message
-          echo "" >> /tmp/message
-          echo '```patch' >> /tmp/message
-          cat /tmp/full-diff.txt  >> /tmp/message
-          echo '```' >> /tmp/message
-          echo "</details>" >> /tmp/message
-      - name: Prepare success message
-        if: ${{ success() }}
+          mvn -V -e -B -ntp verify -Dmaven.javadoc.skip=false -DtrimStackTrace=false -Pit-tests
+      - name: Package test output files
+        if: ${{ failure() || success() }}
+        run: find . -name surefire-reports -o -name failsafe-reports -o -name error-screenshots | tar -czf tests-report-e2e-dev.tgz -T -
+      - uses: actions/upload-artifact@v3
+        if: ${{ failure() || success() }}
+        with:
+          name: tests-output
+          path: tests-report-*.tgz
+  e2e-prod-tests:
+    name: End-to-end tests (Production)
+    needs: [changes]
+    if: ${{ needs.changes.outputs.validation-required == 'true' }}
+    timeout-minutes: 30
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+      - name: Set up Java
+        uses: actions/setup-java@v3
+        with:
+          java-version: ${{ env.JAVA_VERSION }}
+          distribution: 'temurin'
+          cache: maven
+      - uses: browser-actions/setup-chrome@latest
+        with:
+          chrome-version: stable
+      - name: Build
         run: |
           set -x -e -o pipefail
-          echo "# Format Checker Report" >> /tmp/message
-          echo "" >> /tmp/message
-          echo "All files are correctly formatted" >> /tmp/message
-      - name: Comment PR
-        if: ${{ always() }}
-        uses: thollander/actions-comment-pull-request@v2
+          mvn -V -e -B -ntp -DskipTests -Dmaven.javadoc.skip=false install
+      - name: End-to-end Test (Production mode)
+        run: |
+          set -x -e -o pipefail
+          mvn -V -e -B -ntp verify -Dmaven.javadoc.skip=false -DtrimStackTrace=false -Pit-tests,production
+      - name: Package test output files
+        if: ${{ failure() || success() }}
+        run: find . -name surefire-reports -o -name failsafe-reports -o -name error-screenshots | tar -czf tests-report-e2e-prod.tgz -T -
+      - uses: actions/upload-artifact@v3
+        if: ${{ failure() || success() }}
         with:
-          filePath: /tmp/message
-          comment_tag: formatting-check
-      - name: Add format required label to PR
-        if: ${{ failure() && steps.spotlessCheck.conclusion == 'failure' }}
-        uses: actions/github-script@v6
+          name: tests-output
+          path: tests-report-*.tgz
+  test-results:
+    permissions:
+      issues: read
+      checks: write
+      pull-requests: write
+    if: ${{ always() }}
+    needs: [changes, build-and-test, e2e-dev-tests, e2e-prod-tests]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
         with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const { owner, repo } = context.repo;
-            const prNumber = context.payload.pull_request.number;
-
-            await github.rest.issues.addLabels({
-              owner,
-              repo,
-              issue_number: prNumber,
-              labels: ['format:required'],
-            });
-      - name: Add format checked label to PR
-        if: ${{ success() }}
-        uses: actions/github-script@v6
+          ref: ${{ github.event.pull_request.head.sha }}
+      - uses: actions/download-artifact@v3
+        if: ${{ always() && needs.changes.outputs.validation-required == 'true' }}
         with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const { owner, repo } = context.repo;
-            const prNumber = context.payload.pull_request.number;
-
-            await github.rest.issues.addLabels({
-              owner,
-              repo,
-              issue_number: prNumber,
-              labels: ['format:checked'],
-            });
-
-          
-
-    
+          name: tests-output
+      - name: Extract downloaded files
+        if: ${{ always() && needs.changes.outputs.validation-required == 'true' }}
+        run: for i in *.tgz; do tar xvf $i; done
+      - name: Publish Unit Test Results
+        if: ${{ always() && needs.changes.outputs.validation-required == 'true' }}
+        uses: EnricoMi/publish-unit-test-result-action@v2
+        with:
+          junit_files: "**/target/*-reports/TEST*.xml"
+      - name: Set Failure Status
+        if: ${{ always() && needs.changes.outputs.validation-required == 'true' && (needs.build-and-test.result != 'success' || needs.e2e-dev-tests.result != 'success' || needs.e2e-prod-tests.result != 'success') }}
+        run: |
+          echo "🚫 THERE ARE TEST MODULES WITH FAILURES or BEEN CANCELLED" | tee -a $GITHUB_STEP_SUMMARY
+          exit 1
+      - name: Set validation skipped status
+        if: ${{ always() && needs.changes.outputs.validation-required == 'false' }}
+        run: |
+          echo "✅ Pull request only contains changes on files ignored by validation workflow" | tee -a $GITHUB_STEP_SUMMARY && exit 0
